### ISSUE TITLE
Image names with spaces aren't set as background-image for the file div

### ISSUE THREAD

**Issue by yhancik** [kodedninja/ntain#1]
There seem to be a bug with files that have a space in their name:

Filename with no space:
`<div class="file" style="background-image: url(files/DESKTOP_3D.PNG);"><span class="file-name">DESKTOP_3D.PNG</span><span class="file-size data">802005 bytes</span><a class="download-link data" href="dat://e6ad4e74687a3b60616a85d8277ffbaaaf0ca79cd74756be7b9c45ece815d68c/files/DESKTOP_3D.PNG" download="DESKTOP_3D.PNG">Download</a><a class="delete-link data" href="#" data-target="DESKTOP_3D.PNG">Delete</a></div>`

Filename with space:
`<div class="file"><span class="file-name">DESKTOP 3D.PNG</span><span class="file-size data">802005 bytes</span><a class="download-link data" href="dat://e6ad4e74687a3b60616a85d8277ffbaaaf0ca79cd74756be7b9c45ece815d68c/files/DESKTOP 3D.PNG" download="DESKTOP 3D.PNG">Download</a><a class="delete-link data" href="#" data-target="DESKTOP 3D.PNG">Delete</a></div>`

**Comment by kodedninja** [comment]
Sorry, I was afk 😄 I'll have a look in a moment

**Comment by kodedninja** [comment]
@yhancik it's fixed now. Will be included in the next update.
